[project]
name = "scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "openpyxl>=3.1.5",
    "pydantic>=2.9.2",
    "streamlit>=1.40.1",
    "typer>=0.13.0",
]
